import Head from 'next/head'
import { useContext } from 'react'

import { Checkout } from '../../container/checkout'
import { Context } from '../../context'

export default function ProcessView () {
  const {
    setAlertBox,
    setCountItemProduct,
    locationStr,
    setModalLocation
  } = useContext(Context)
  return (
    <div >
      <Head>
        <title>Delibery Proceso  </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Checkout
        locationStr={locationStr}
        setAlertBox={setAlertBox}
        setCountItemProduct={setCountItemProduct}
        setModalLocation={setModalLocation}
      />
    </div>
  )
}
