import Head from 'next/head'
import { Promos } from '@/container/Promos'

export default function PromoView () {
  return (
    <div >
      <Head>
        <title>Delivery Promos </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Promos />
    </div>
  )
}
