import Head from 'next/head'
import { CheckoutFinalizar } from '../../../container/checkoutFinalizar'

export default function procesoFinalView () {
  return (
    <div >
      <Head>
        <title>Delibery Proceso  final </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <CheckoutFinalizar />

    </div>
  )
}
