import Head from 'next/head'
import { Categories } from 'container/categorias'

export default function View () {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Categories />
    </div>
  )
}
