import Head from 'next/head'
import { useQuery } from '@apollo/client'
import { Historial } from '../../container/history'
import { GET_ALL_FAV_STORE } from '../../container/profile/queries'
export default function HomeView () {
  const { data: dataFav } = useQuery(GET_ALL_FAV_STORE)
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Historial dataFav={dataFav?.getFavorite || []} />
    </div>
  )
}
