/* eslint-disable no-unused-vars */
import Head from 'next/head'
import { withIronSessionSsr } from 'iron-session/next'
import { cookie } from 'utils'

import { Profile } from '../../container/profile'

export default function ProfileView () {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Profile />
    </div>
  )
}

export const getServerSideProps = withIronSessionSsr(async function getServerSideProps ({ req, res, query: queryRouter }) {
  try {
    const { id } = queryRouter || {}
    const { user } = req.session || {}
    const { storeUserId } = user || {}
    const url = `${process.env.URL_BASE}api/graphql`
    const query = `
      query getOneStore($StoreName: String, $idStore: ID){
        getOneStore(idStore: $idStore, StoreName: $StoreName) {
          idStore
          uState
        }
      }
      `
    const variables = {
      idStore: id
    }
    fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ query, variables })
    }).then(response => { return response.json() })
      .then(data => {
        let bool = false
        if (data?.data?.getOneStore?.uState === '1') {
          bool = true
        }
      })
    return {
      props: {
        storeUserId: storeUserId || null,
        idStore: id || null
      }
    }
  } catch (error) {
    return {}
  }
},
cookie
)
