// import { ConfirmCheckout } from '@/container/confirmCheckout'
// import { useLazyQuery, useMutation } from '@apollo/client'
import Head from 'next/head'
// import { useRouter } from 'next/router'
// import { useEffect, useState } from 'react'
// import { CREATE_ONE_STORE_PEDIDO } from '../../../../container/confirmCheckout/queries'
// import { GET_ONE_PRODUCTS_FOOD } from '../../../../container/queries'

export default function procesoConfirmView () {
  // const location = useRouter()
  // const [payMethod] = useState(1)
  // const [recoger, setRecoger] = useState(1)
  // const { code, idstore, pid } = location.query
  // const [productFoodsOne, { data: dataOneProduct }] = useLazyQuery(GET_ONE_PRODUCTS_FOOD)
  // useEffect(() => {
  //   productFoodsOne({ variables: { pid } })
  // }, [code, idstore, pid])
  // const [createOnePedidoStore] = useMutation(CREATE_ONE_STORE_PEDIDO, {
  //   onError: () => { }
  // })
  // const handleSubmitPedido = async e => {
  //   await createOnePedidoStore({
  //     variables: {
  //       input: {
  //         id: 'MjE3NjcxMDUxODgxMjEzMTYwMA==',
  //         pId: pid,
  //         idStore: idstore,
  //         pPStateP: 1,
  //         pDatMod: 1,
  //         unidProducts: 1,
  //         pCodeRef: code,
  //         payMethodPState: payMethod,
  //         pPRecoger: recoger
  //       }
  //     }
  //   })
  // }
  return (
    <div >
      <Head>
        <title>Delibery pedido </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      {/* <ConfirmCheckout
        code={code}
        dataOneProduct={dataOneProduct?.productFoodsOne || {}}
        handleSubmitPedido={handleSubmitPedido}
        idstore={idstore}
        pid={pid}
      /> */}
    </div>
  )
}
