import Head from 'next/head'

export default function CreditView () {
  return (
    <div >
      <Head>
        <title>Delibery de Historia </title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
    </div>
  )
}
